import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
const out = mkdtempSync(join(tmpdir(), '3tris-test-'));
try {
  execFileSync(process.execPath, ['node_modules/typescript/bin/tsc', '--module', 'commonjs', '--target', 'es2022', '--skipLibCheck', '--outDir', out, 'src/lib/game/engine.ts', 'src/lib/game/settings.ts', 'src/lib/game/records.ts']);
  writeFileSync(join(out, 'package.json'), '{"type":"commonjs"}');
  const require = createRequire(import.meta.url);
  const { Engine } = require(join(out, 'engine.js'));
  const { DEFAULT_SETTINGS } = require(join(out, 'settings.js'));
  const { EMPTY_RECORDS, applyRun, loadRecords } = require(join(out, 'records.js'));
  const makeClear = (mode, initialLines, rows) => {
    const engine = new Engine(DEFAULT_SETTINGS);
    engine.mode = mode;
    engine.start();
    engine.lines = initialLines;
    engine.timeMs = 12345;
    for (let y = 40 - rows; y < 40; y++) engine.grid[y] = Array.from({ length: 10 }, (_, x) => x === 4 ? null : { id: 'T', lockedAt: 0 });
    engine.active = { id: 'I', x: 2, y: 20, rot: 1, lastKick: 0 };
    const events = [];
    engine.on(e => events.push(e));
    engine.hardDrop();
    return { engine, events };
  };
  for (const [initial, rows] of [[39, 1], [38, 4]]) {
    const { engine, events } = makeClear('sprint', initial, rows);
    const finishTime = engine.timeMs;
    engine.step(0.2, false);
    assert.equal(engine.phase, 'over');
    assert.equal(engine.level, 1);
    assert.equal(engine.timeMs, finishTime);
    assert.equal(events.filter(e => e.type === 'over' && e.completed).length, 1);
    assert.equal(engine.active, null);
    engine.step(1, false);
    assert.equal(engine.timeMs, finishTime);
    engine.restart();
    assert.equal(engine.mode, 'sprint');
    assert.equal(engine.lines, 0);
    assert.equal(engine.phase, 'playing');
  }
  const { engine: endless } = makeClear('endless', 39, 1);
  endless.step(0.2, false);
  assert.equal(endless.phase, 'playing');
  assert.equal(endless.level, 5);
  const { engine: partial } = makeClear('sprint', 0, 1);
  partial.step(0.2, false);
  assert.equal(partial.phase, 'playing');
  assert.equal(partial.timeMs, 12545);
  partial.pause(); partial.step(2, false);
  assert.equal(partial.timeMs, 12545);
  const storage = new Map();
  globalThis.window = {};
  globalThis.localStorage = { getItem: k => storage.get(k) ?? null, setItem: (k,v) => storage.set(k,v) };
  const run = { score: 1200, lines: 40, level: 1, timeMs: 90000, completed: true };
  let result = applyRun(EMPTY_RECORDS, run, 'sprint');
  assert.equal(result.flags.sprint, true);
  assert.equal(loadRecords('sprint').sprintBestMs, 90000);
  assert.equal(loadRecords().highScore, 0);
  result = applyRun(result.records, { ...run, timeMs: 100000 }, 'sprint');
  assert.equal(result.flags.sprint, false);
  result = applyRun(result.records, { ...run, timeMs: 1000, completed: false }, 'sprint');
  assert.equal(result.records.sprintBestMs, 90000);
  result = applyRun(result.records, { ...run, timeMs: 80000 }, 'sprint');
  assert.equal(result.flags.sprint, true);
  assert.equal(loadRecords('sprint').sprintBestMs, 80000);
  applyRun(EMPTY_RECORDS, run);
  assert.equal(loadRecords().highScore, 1200);
  assert.equal(loadRecords('sprint').sprintBestMs, 80000);
  console.log('Passed: sprint finish/overshoot, timer, pause, restart, endless progression, record persistence and mode isolation.');
} finally { rmSync(out, { recursive: true, force: true }); }
